service: ggf-server # NOTE: update this with your service name

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-s3-remover

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  environment:
    SITE_HOME: http://catseven.cafe24.com

package:
  include:
    - ./src/schema.graphql
    - ./src/templates/**/*.html

functions:
  server:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: post
          cors: true
  playground:
    handler: src/server.playground
    events:
      - http:
          path: /
          method: get
          cors: true

custom:
  remover:
    buckets:
      - server
      - playground
