AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  Server:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/server.handler
      Runtime: nodejs8.10
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /
            Method: Post
  Playground:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/server.playground
      Runtime: nodejs8.10
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /
            Method: Get
